#ifndef GOL_BUSINESS_PARALLEL_GLOBAL_H
#define GOL_BUSINESS_PARALLEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GOL_BUSINESS_PARALLEL_LIBRARY)
#define GOL_BUSINESS_PARALLEL_API Q_DECL_EXPORT
#else
#define GOL_BUSINESS_PARALLEL_API Q_DECL_IMPORT
#endif

#endif // GOL_BUSINESS_PARALLEL_GLOBAL_H
